name: Notify Telegram on PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send message to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="A new Pull Request was created for the main branch: ${{ github.event.pull_request.html_url }}"

